spring.application.name=piedraazul-agenda-service
server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/piedraazul_agenda
spring.datasource.username=appuser
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/api/**

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8082}